global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'redis'
    static_configs:
      - targets: ['localhost:6379']

  - job_name: 'kafka'
    static_configs:
      - targets: ['10.89.1.8:9092']

  - job_name: 'spring-boot-demo'
    metrics_path: '/actuator/prometheus' # 指定抓取的路徑
    static_configs:
      - targets: ['10.89.1.3:9999']
        labels:
          nodename: 'app-demo'
